//
//  Base.swift
//  Charms of Belarus
//
//  Created by Pavel on 6/29/20.
//  Copyright © 2020 Pavel. All rights reserved.
//

import Foundation

struct Base {
    let cities: [City] = [
        City(name: "Minsk", attractions: [
            Attraction(attractionName: "Church of Saints Simon and Helena", image: #imageLiteral(resourceName: "IMG_8596"), description: "Church of Saints Simon and Helena (Belarusian: Касцёл святых Сымона і Алены) (Polish: Kościół św. Szymona i św. Heleny w Mińsku) also known as the Red Church (Belarusian: Чырвоны касцёл) is a Roman Catholic church on Independence Square in Minsk, Belarus. This neo-Romanesque church was designed by Polish architects Tomasz Pajzderski and Władysław Marconi. The cornerstone was laid in 1905 and the church was completed in 1910. The bricks for its walls were sourced from Częstochowa, whilst the roof tiles came from Włocławek. Its construction was financed by Edward Woyniłłowicz (1847-1928), a prominent Belarusian-Polish landowner, businessman and civic activist. The church was named and consecrated in memory of Woyniłłowicz's two deceased children, Szymon and Helena.", link: "https://en.wikipedia.org/wiki/Church_of_Saints_Simon_and_Helena"),
            Attraction(attractionName: "Holy Spirit Cathedral", image: #imageLiteral(resourceName: "IMG_0249"), description: "The Holy Spirit Cathedral (Belarusian: Кафедральны сабор Сашэсця Святога Духа) in Minsk, Belarus is dedicated to the Holy Spirit. It is the central cathedral of the Belarusian Orthodox Church.The Theotokos icon in the Cathedral has been reported as miraculous. The cathedral dates back to 1633–1642, when the Bernardine monastery was built, at a time when the city was in centre of the Polish–Lithuanian Commonwealth. The building was damaged by fire in 1741 and required the reconstruction of the entire monastery.", link: "https://en.wikipedia.org/wiki/Holy_Spirit_Cathedral_(Minsk)"),
            Attraction(attractionName: "Cathedral of Saint Virgin Mary", image: #imageLiteral(resourceName: "marii2"), description: "Cathedral of the Holy Name of Mary (Belarusian: Архікатэдральны касцёл Найсвяцейшага Імя Найсвяцейшай Панны Марыі, Archikatedralny kascioł Imia Najsviaciejšaj Panny Maryi) is a Roman Catholic baroque cathedral in Minsk. It is the seat of the Roman Catholic Archdiocese of Minsk-Mohilev. It was built under the Polish rule in 1710 as a church for the Jesuit house. In 1793, after the Russian conquest of Belarusian part of the Polish-Lithuanian Commonwealth, the Jesuit order was banned and the church got a local status. Soon, after creation of the Minsk diocese, the church became the local cathedral.The Cathedral was heavily damaged in a fire in 1797, but was later fully renewed. In 1869, the Minsk diocese was liquidated and the church got a parafial status. In November 1917, the diocese was restored; Zygmunt Lazinski was appointed as a bishop. In 1920, Lazinski was arrested by Soviet authorities, the cathedral was closed down in 1934.", link: "https://en.wikipedia.org/wiki/Cathedral_of_the_Holy_Name_of_Saint_Virgin_Mary")]),
        City(name: "Grodno", attractions: [
            Attraction(attractionName: "Old Grodno Castle", image: #imageLiteral(resourceName: "Гродно_Старый_замок_02"), description: "The Old Grodno Castle (also known as the Grodno Upper Castle and Bathory's Castle) originated in the 11th century as the seat of a dynasty of Black Ruthenian rulers, descended from a younger son of Yaroslav the Wise of Kiev. The 13th-century keep of the castle belonged to a type of Belarusian defensive tower represented by the Tower of Kamyanyets. Vytautas the Great added five Brick Gothic towers in 1391–98, transforming the castle into one of his main residences. Casimir IV Jagiellon also favoured Hrodna over Lithuania's official capital. It was there that the Polish Crown was offered to him, and it was there that he died in 1492.The next notable tenant of the castle was Stephen Báthory who envisaged Hrodna as the capital of his vast empire in Eastern Europe. He engaged Scotto of Parma to replace the Vytautas Castle with his own residence in the advanced Renaissance taste of Northern Italy.", link: "https://en.wikipedia.org/wiki/Old_Grodno_Castle"),
            Attraction(attractionName: "New Hrodna Castle", image: #imageLiteral(resourceName: "Belarus-Hrodna-New_and_Old_Castles-1"), description: "The New Castle in Hrodna, Belarus is a royal palace of Augustus III of Poland and Stanisław August Poniatowski where the famous Grodno Sejm took place in 1793. New Hrodna Castle is 116 metres (381 ft) above sea level.The royal residence was built on the high bank of the Neman River at a little distance from the Old Hrodna Castle which had suffered great dilapidation in the aftermath of the Swedish occupation in the early 18th century. The two castles are joined by a 300-year-old arch bridge. The palace compound was designed by Carl Friedrich Pöppelmann. Construction was carried out between 1734 and 1751 under the supervision of several other Saxon architects, including Johann Friedrich Knöbel and Joachim Daniel von Jauch. The palace was completed under the direction of Giuseppe de Sacco in 1789 and remained home for King Stanisław II August until 1797.", link: "https://en.wikipedia.org/wiki/New_Hrodna_Castle"),
            Attraction(attractionName: "St. Francis Xavier Cathedral", image: #imageLiteral(resourceName: "1280px-Гродно_Костел_Фарный_01"), description: "St. Francis Xavier Cathedral is a Roman Catholic cathedral in Grodno, Belarus. Originally a Jesuit church, it became a cathedral in 1991, when the new diocese of Grodno was erected. The construction of the church started in 1687. The completed building in Baroque style was consecrated in 1705 to St. Francis Xavier. The monastery was dissolved in 1773 and the church became a parish one. The church survived World War II with no serious damage. In 1960 it was officially closed for a public religious services (for 27 years). The communist authorities tried to convert the building into a museum or a concert hall. Despite this the people attended the church every Sunday for a common prayer, songs and rosary. The religious services were restored in 1987. In 1990 the church was granted the title of minor basilica, and a year later it became a cathedral for a diocese of Grodno.", link: "https://en.wikipedia.org/wiki/St._Francis_Xavier_Cathedral,_Grodno")]),
        City(name: "Brest", attractions: [
            Attraction(attractionName: "Brest Fortress", image: #imageLiteral(resourceName: "1280px-BrestFortress7"), description: "Brest Fortress (Belarusian: Брэсцкая крэпасць, Bresckaja krepasć; Polish: Twierdza brzeska), formerly known as Brest-Litoŭsk Fortress, is a 19th-century fortress in Brest in present-day Belarus. In 1965 the title \"Hero Fortress\" was given[by whom?] to the fortress to commemorate the defence of the frontier stronghold during the first week of the German-Soviet War of 1941-1945 when Axis forces invaded the Soviet Union with the launch of Operation Barbarossa on June 22, 1941. The title \"Hero Fortress\" corresponds to the title \"Hero City\" that the Presidium of the Supreme Soviet of the Soviet Union awarded to an eventual total of twelve Soviet cities.The Brest fortress has sustained its original outline of a star shaped fortification since its construction in the early 19th century. The Citadel, the core of the fortress, was on the central island formed by the Bug River and the two branches of the Mukhavets River. The island was skirted by a ring of a two-storied barrack with 4 semi-towers.", link: "https://en.wikipedia.org/wiki/Brest_Fortress"),
            Attraction(attractionName: "Brest Railway Museum", image: #imageLiteral(resourceName: "Parovoz_\"Felix_Dzherzinski\"_in_Brest_museum"), description: "At Brest Railway Museum, see a display of historical locomotives at the first outdoor railway museum in Belarus, opened in 2002. Its collection features 56 units, including steam engines, two steam cranes, retro passenger cabs, and diesel/electric engines. Watch for the Soviet red star on the front of many locomotives. You can explore the interior of several wagons, which are open for visitors. Take a guided tour to learn more about the exhibits and the history of the railway system. Plan your Brest Railway Museum visit and explore what else you can see and do in Brest using our Brest vacation maker app. This museum has a large number of unique railway cars. Definitely worth a visit. There is a small indoor section too. Note that the entrance is on the south side", link: "https://en.wikipedia.org/wiki/Brest_Railway_Museum")])]
}
